tabs:
  fields:
    cms_content:
      label: dynamedia.posts::lang.blocks.section.labels.cms_content
      tab: dynamedia.posts::lang.common.tabs.main
      type: dropdown
      options: \Dynamedia\Posts\Classes\Helpers\Form::getCmsContentOptions
