tabs:
    fields:
        cms_partial:
            label: dynamedia.posts::lang.blocks.section.labels.cms_partial
            tab: dynamedia.posts::lang.common.tabs.main
            type: dropdown
            options: \Dynamedia\Posts\Classes\Helpers\Form::getCmsPartialOptions
