tabs:
    fields:
        content:
            label: dynamedia.posts::lang.blocks.section.labels.html
            tab: dynamedia.posts::lang.common.tabs.main
            type: codeeditor
            language: html
            size: huge
