tabs:
    fields:
        heading:
            tab: dynamedia.posts::lang.common.tabs.main
            span: left
            label: dynamedia.posts::lang.blocks.labels.section_heading
            comment: H2

        sId:
            tab: dynamedia.posts::lang.common.tabs.main
            span: right
            label: dynamedia.posts::lang.blocks.labels.section_id
            preset: heading

        content:
            tab: dynamedia.posts::lang.common.tabs.main
            label: dynamedia.posts::lang.blocks.labels.section_content
            type: richeditor
            size: huge

        image:
            tab: dynamedia.posts::lang.common.tabs.image
            type: nestedform
            usePanelStyles: false
            form: $/dynamedia/posts/config/forms/image/body_section.yaml

        in_contents:
            tab: dynamedia.posts::lang.common.tabs.settings
            type: switch
            label: dynamedia.posts::lang.blocks.labels.in_contents
            default: true
