section:
    name: Section Block
    description: Add a section of content
    fields:
        block:
            type: nestedform
            usePanelStyles: false
            form: $/dynamedia/posts/config/forms/block/basic_section.yaml

html:
    name: HTML Block
    description: Add a block of html
    fields:
        block:
            type: nestedform
            usePanelStyles: false
            form: $/dynamedia/posts/config/forms/block/html.yaml

image:
    name: Image Block
    description: Add an image block
    fields:
        block:
            type: nestedform
            usePanelStyles: false
            form: $/dynamedia/posts/config/forms/image/body.yaml

cms_content:
    name: CMS Content
    description: Add CMS content block
    fields:
        block:
            type: nestedform
            usePanelStyles: false
            form: $/dynamedia/posts/config/forms/block/cms_content.yaml

#cms_partial:
#    name: CMS Partial
#    description: Add a CMS partial
#    fields:
#        block:
#            type: nestedform
#            usePanelStyles: false
#            form: $/dynamedia/posts/config/forms/block/cms_partial.yaml
