tabs:
  fields:
    type:
      tab: dynamedia.posts::lang.seo.tabs.general
      label: Post Type
      type: dropdown
      options:
        Article: Article
        BlogPosting: Blog Post
        NewsArticle: News Article
    about:
      tab: dynamedia.posts::lang.seo.tabs.general
      label: Post is About
    keywords:
      tab: dynamedia.posts::lang.seo.tabs.general
      label: Keywords
      type: taglist
      mode: array
    title:
      tab: dynamedia.posts::lang.seo.tabs.search
      label: Page Title
    description:
      tab: dynamedia.posts::lang.seo.tabs.search
      label: Meta Description
      type: textarea
    opengraph_title:
      tab: dynamedia.posts::lang.seo.tabs.opengraph
      label: Title
    opengraph_description:
      tab: dynamedia.posts::lang.seo.tabs.opengraph
      label: Description
      type: textarea
    twitter_title:
      tab: dynamedia.posts::lang.seo.tabs.twitter
      label: Title
    twitter_description:
      tab: dynamedia.posts::lang.seo.tabs.twitter
      label: Description
      type: textarea

