tabs:
  fields:
    type:
      tab: General
      label: Post Type
      type: dropdown
      options:
        Article: Article
        BlogPosting: Blog Post
        NewsArticle: News Article
    about:
      tab: General
      label: Post is About
    keywords:
      tab: General
      label: Keywords
      type: taglist
      mode: array
    title:
      tab: Search
      label: Page Title
    description:
      tab: Search
      label: Meta Description
      type: textarea
    opengraph_title:
      tab: Facebook OG
      label: Title
    opengraph_description:
      tab: Facebook OG
      label: Description
      type: textarea
    twitter_title:
      tab: Twitter Card
      label: Title
    twitter_description:
      tab: Twitter Card
      label: Description
      type: textarea

