tabs:
  fields:
    title:
      tab: Search
      label: Page Title
    description:
      tab: Search
      label: Meta Description
      type: textarea
    opengraph_title:
      tab: Facebook OG
      label: Title
    opengraph_description:
      tab: Facebook OG
      label: Description
      type: textarea
    twitter_title:
      tab: Twitter Card
      label: Title
    twitter_description:
      tab: Twitter Card
      label: Description
      type: textarea
    json_ld:
      tab: JSON+LD
      label: PLACEHOLDER FOR NESTED FORM

